version: '3.3'

services:
    webserver:

        image: nginx:latest
        ports:

            - 80:80
        volumes:
            - ./www:/usr/share/nginx/html
            - ./ngincx:/etc/nginx/conf.d/